name: "Run artifact-size-analyzer"
author: David Sveningsson
description: "Analyze artifact sizes in a pull request using artifact-size-analyzer and upload the result as an artifact."

branding:
  icon: git-pull-request
  color: blue

inputs:
  config-file:
    description: "Path to the artifact configuration file."
    required: true
  artifact-name:
    description: "Name for the uploaded artifact."
    required: true
  output-file:
    description: "Path to the output file produced by the analyzer."
    required: false
    default: "temp/artifact-size.json"
  version:
    description: "Optional npm package version (e.g. 1.2.3). Default uses the version specified in package.json or latest if not specified."
    required: false
  use-local:
    description: "When set to 'true', run the local ./bin/artifact-size-analyzer from the repository instead of using npx. Caller must checkout the repository when using this option."
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - id: pick-cmd
      name: Decide command
      shell: bash
      run: |
        set -euo pipefail
        if [ "${{ inputs.use-local }}" = "true" ]; then
          CMD='node ./bin/artifact-size-analyzer'
        elif [ -n "${{ inputs.version }}" ]; then
          CMD="npx artifact-size-analyzer@${{ inputs.version }}"
        else
          CMD='npx artifact-size-analyzer'
        fi
        echo "cmd=$CMD" | tee -a "$GITHUB_OUTPUT"

    - name: Run artifact-size-analyzer
      id: run
      shell: bash
      run: |
        ${{ steps.pick-cmd.outputs.cmd }} analyze \
          --config-file "${{ inputs.config-file }}" \
          --output-file "${{ inputs.output-file }}" \
          --format json

    - name: Upload artifact
      uses: actions/upload-artifact@v6
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.output-file }}
