name: "Compare pull-request-bundle-analyzer results"
author: David Sveningsson
description: "Download two analyzer artifacts, run the `compare` command and save markdown output."

branding:
  icon: git-pull-request
  color: blue

inputs:
  base-artifact:
    description: "Artifact name for the base run (uploaded by analyze action)."
    required: true
  current-artifact:
    description: "Artifact name for the current run (uploaded by analyze action)."
    required: true
  base-name:
    description: "File name inside the base artifact that contains the analyzer output."
    required: false
    default: "artifact-size.json"
  current-name:
    description: "File name inside the current artifact that contains the analyzer output."
    required: false
    default: "artifact-size.json"
  version:
    description: "Optional npm package version (e.g. 1.2.3). If provided, runs `npx pull-request-bundle-analyzer@<version>`."
    required: false
  use-local:
    description: "When set to 'true', run the local ./bin/bundle-analyzer from the repository instead of using npx. Caller must checkout the repository when using this option."
    required: false
    default: "false"

outputs:
  markdown:
    description: "The comparison result as markdown."
    value: ${{ steps.compare.outputs.markdown }}
  text:
    description: "The comparison result as plain text."
    value: ${{ steps.compare.outputs.text }}
  json:
    description: "The comparison result as JSON."
    value: ${{ steps.compare.outputs.json }}

runs:
  using: "composite"
  steps:
    - name: Download base artifact
      uses: actions/download-artifact@v6
      with:
        name: ${{ inputs.base-artifact }}
        path: temp/base

    - name: Download current artifact
      uses: actions/download-artifact@v6
      with:
        name: ${{ inputs.current-artifact }}
        path: temp/current

    - id: pick-cmd
      name: Decide command
      shell: bash
      run: |
        set -euo pipefail
        if [ "${{ inputs.use-local }}" = "true" ]; then
          CMD='node ./bin/bundle-analyzer'
        elif [ -n "${{ inputs.version }}" ]; then
          CMD="npx pull-request-bundle-analyzer@${{ inputs.version }}"
        else
          CMD='npx pull-request-bundle-analyzer'
        fi
        echo "cmd=$CMD" | tee -a "$GITHUB_OUTPUT"

    - name: Ensure base artifact exists
      shell: bash
      run: |
        tree temp/base
        cat "temp/base/${{ inputs.base-name }}"

    - name: Ensure current artifact exists
      shell: bash
      run: |
        tree temp/current
        cat "temp/base/${{ inputs.current-name }}"

    - id: compare
      name: Compare results and set output
      shell: bash
      run: |
        ${{ steps.pick-cmd.outputs.cmd }} compare \
          --base "temp/base/${{ inputs.base-name }}" \
          --current "temp/current/${{ inputs.current-name }}" \
          --format markdown \
          --output-github markdown:markdown \
          --output-github text:text \
          --output-github json:json
